use_frameworks!

platform :ios, '9.0'

target 'YFBinarySort_Example' do
  pod 'YFBinarySort', :path => '../'

  target 'YFBinarySort_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
